In [125]:
import numpy as np
import pandas as pd

In [126]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\ADMIN\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\ADMIN\AppData\Local\Programs\Python\Python314\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [127]:
sales = pd.read_excel('.original_hackathon_data.xlsx',sheet_name = 'Sales')
finance = pd.read_excel('.original_hackathon_data.xlsx',sheet_name = 'Financial_plan')
product = pd.read_excel('.original_hackathon_data.xlsx',sheet_name = 'Products_parameters')

In [128]:
sales.head()

,ProductID,Product_name,Type,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,...,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12
0,P001,Product 001,Sales,56,47,43,40,50,72,66,...,51,46,45,52,77,67,62,55,43,39
1,P001,Product 001,Inventory_level,219,172,129,89,39,237,171,...,92,46,1,237,160,93,31,392,349,310
2,P002,Product 002,Sales,34,29,34,29,28,32,37,...,31,37,41,40,30,35,38,37,43,32
3,P002,Product 002,Inventory_level,200,171,137,108,80,48,11,...,169,132,91,51,21,284,246,209,166,134
4,P003,Product 003,Sales,67,62,68,55,57,59,61,...,58,51,64,73,69,78,71,68,82,80

In [129]:
sales.shape

(500, 39)

In [130]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 39 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ProductID     500 non-null    str
 1   Product_name  500 non-null    str
 2   Type          500 non-null    str
 3   2023-01       500 non-null    int64
 4   2023-02       500 non-null    int64
 5   2023-03       500 non-null    int64
 6   2023-04       500 non-null    int64
 7   2023-05       500 non-null    int64
 8   2023-06       500 non-null    int64
 9   2023-07       500 non-null    int64
 10  2023-08       500 non-null    int64
 11  2023-09       500 non-null    int64
 12  2023-10       500 non-null    int64
 13  2023-11       500 non-null    int64
 14  2023-12       500 non-null    int64
 15  2024-01       500 non-null    int64
 16  2024-02       500 non-null    int64
 17  2024-03       500 non-null    int64
 18  2024-04       500 non-null    int64
 19  2024-05       500 non-null    int64
 20  2024-06       500 non-null    int64
 21  2024-07       500 non-null    int64
 22  2024-08       500 non-null    int64
 23  2024-09       500 non-null    int64
 24  2024-10       500 non-null    int64
 25  2024-11       500 non-null    int64
 26  2024-12       500 non-null    int64
 27  2025-01       500 non-null    int64
 28  2025-02       500 non-null    int64
 29  2025-03       500 non-null    int64
 30  2025-04       500 non-null    int64
 31  2025-05       500 non-null    int64
 32  2025-06       500 non-null    int64
 33  2025-07       500 non-null    int64
 34  2025-08       500 non-null    int64
 35  2025-09       500 non-null    int64
 36  2025-10       500 non-null    int64
 37  2025-11       500 non-null    int64
 38  2025-12       500 non-null    int64
dtypes: int64(36), str(3)
memory usage: 152.5 KB

In [131]:
sales.describe(include = 'all')

,ProductID,Product_name,Type,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,...,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12
count,500,500,500,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000,...,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.00000,500.000000,500.000000
unique,250,250,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,P001,Product 001,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2,2,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,217.848000,174.662000,142.304000,141.43600,159.408000,198.550000,236.448000,...,181.802000,185.142000,191.824000,202.834000,209.712000,217.44800,207.568000,211.99400,214.262000,218.326000
std,NaN,NaN,NaN,213.003394,168.792386,137.364003,176.55649,205.163344,269.168734,300.715278,...,223.755393,233.800152,256.814229,252.395804,244.537011,248.86362,308.452335,311.74386,288.843464,288.730182
min,NaN,NaN,NaN,5.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000
25%,NaN,NaN,NaN,71.750000,63.750000,52.000000,53.00000,50.000000,53.000000,58.750000,...,57.000000,56.000000,55.000000,57.000000,59.000000,70.00000,61.000000,56.00000,55.000000,55.000000
50%,NaN,NaN,NaN,138.000000,117.000000,95.000000,93.00000,94.000000,99.500000,120.000000,...,103.000000,100.500000,103.000000,108.500000,117.000000,128.50000,106.000000,107.00000,102.000000,121.000000
75%,NaN,NaN,NaN,302.500000,233.500000,175.250000,161.00000,183.250000,211.250000,291.500000,...,219.000000,202.250000,215.500000,227.250000,270.250000,264.25000,216.250000,207.50000,242.500000,264.000000
max,NaN,NaN,NaN,1639.000000,1250.000000,901.000000,2091.00000,1974.000000,2048.000000,2134.000000,...,1663.000000,1591.000000,2415.000000,2004.000000,1737.000000,1727.00000,3222.000000,3063.00000,2802.000000,2582.000000

In [132]:
# Checking the null values
sales.isnull().sum()

ProductID       0
Product_name    0
Type            0
2023-01         0
2023-02         0
2023-03         0
2023-04         0
2023-05         0
2023-06         0
2023-07         0
2023-08         0
2023-09         0
2023-10         0
2023-11         0
2023-12         0
2024-01         0
2024-02         0
2024-03         0
2024-04         0
2024-05         0
2024-06         0
2024-07         0
2024-08         0
2024-09         0
2024-10         0
2024-11         0
2024-12         0
2025-01         0
2025-02         0
2025-03         0
2025-04         0
2025-05         0
2025-06         0
2025-07         0
2025-08         0
2025-09         0
2025-10         0
2025-11         0
2025-12         0
dtype: int64

In [133]:
sales.duplicated().sum()

np.int64(0)

In [134]:
sales.columns = sales.columns.str.lower()

In [135]:
sales.columns

Index(['productid', 'product_name', 'type', '2023-01', '2023-02', '2023-03',
       '2023-04', '2023-05', '2023-06', '2023-07', '2023-08', '2023-09',
       '2023-10', '2023-11', '2023-12', '2024-01', '2024-02', '2024-03',
       '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09',
       '2024-10', '2024-11', '2024-12', '2025-01', '2025-02', '2025-03',
       '2025-04', '2025-05', '2025-06', '2025-07', '2025-08', '2025-09',
       '2025-10', '2025-11', '2025-12'],
      dtype='str')

In [136]:
sales.rename(columns = {'productid':'product_id'},inplace = True)
sales.columns

Index(['product_id', 'product_name', 'type', '2023-01', '2023-02', '2023-03',
       '2023-04', '2023-05', '2023-06', '2023-07', '2023-08', '2023-09',
       '2023-10', '2023-11', '2023-12', '2024-01', '2024-02', '2024-03',
       '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09',
       '2024-10', '2024-11', '2024-12', '2025-01', '2025-02', '2025-03',
       '2025-04', '2025-05', '2025-06', '2025-07', '2025-08', '2025-09',
       '2025-10', '2025-11', '2025-12'],
      dtype='str')

In [137]:
sales1 = sales[sales['type']=='Sales'].melt(
                    id_vars = ['product_id','product_name'],
                    value_vars = ['2023-01', '2023-02', '2023-03',
       '2023-04', '2023-05', '2023-06', '2023-07', '2023-08', '2023-09',
       '2023-10', '2023-11', '2023-12', '2024-01', '2024-02', '2024-03',
       '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09',
       '2024-10', '2024-11', '2024-12', '2025-01', '2025-02', '2025-03',
       '2025-04', '2025-05', '2025-06', '2025-07', '2025-08', '2025-09',
       '2025-10', '2025-11', '2025-12'],
       var_name = 'record_date', value_name = 'sales_quantity'

       )

In [138]:
sales1.head()

  product_id product_name record_date  sales_quantity
0       P001  Product 001     2023-01              56
1       P002  Product 002     2023-01              34
2       P003  Product 003     2023-01              67
3       P004  Product 004     2023-01              98
4       P005  Product 005     2023-01              35

In [139]:
inventory = sales[sales['type']=='Inventory_level'].melt(
                    id_vars = ['product_id','product_name'],
                    value_vars = ['2023-01', '2023-02', '2023-03',
       '2023-04', '2023-05', '2023-06', '2023-07', '2023-08', '2023-09',
       '2023-10', '2023-11', '2023-12', '2024-01', '2024-02', '2024-03',
       '2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09',
       '2024-10', '2024-11', '2024-12', '2025-01', '2025-02', '2025-03',
       '2025-04', '2025-05', '2025-06', '2025-07', '2025-08', '2025-09',
       '2025-10', '2025-11', '2025-12'],
       var_name = 'record_date', value_name = 'inventory_quantity'

       )

In [140]:
inventory.head()

  product_id product_name record_date  inventory_quantity
0       P001  Product 001     2023-01                 219
1       P002  Product 002     2023-01                 200
2       P003  Product 003     2023-01                 232
3       P004  Product 004     2023-01                 518
4       P005  Product 005     2023-01                 100

In [141]:
sales.shape

(500, 39)

In [142]:
sales1.shape

(9000, 4)

In [143]:
inventory.shape

(9000, 4)

In [144]:
sales = pd.merge(sales1, inventory, how = 'inner', on=['product_id','product_name','record_date'])

sales.head()

  product_id product_name record_date  sales_quantity  inventory_quantity
0       P001  Product 001     2023-01              56                 219
1       P002  Product 002     2023-01              34                 200
2       P003  Product 003     2023-01              67                 232
3       P004  Product 004     2023-01              98                 518
4       P005  Product 005     2023-01              35                 100

In [145]:
sales = sales.drop(columns = 'product_name')
sales.head()

  product_id record_date  sales_quantity  inventory_quantity
0       P001     2023-01              56                 219
1       P002     2023-01              34                 200
2       P003     2023-01              67                 232
3       P004     2023-01              98                 518
4       P005     2023-01              35                 100

In [146]:
sales.tail()

     product_id record_date  sales_quantity  inventory_quantity
8995       P246     2025-12              32                 497
8996       P247     2025-12              65                 508
8997       P248     2025-12             116                   0
8998       P249     2025-12             134                  11
8999       P250     2025-12              29                 169

In [147]:
sales['record_date'] = pd.to_datetime(sales['record_date'])

In [148]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          9000 non-null   str
 1   record_date         9000 non-null   datetime64[us]
 2   sales_quantity      9000 non-null   int64
 3   inventory_quantity  9000 non-null   int64
dtypes: datetime64[us](1), int64(2), str(1)
memory usage: 281.4 KB

In [149]:
sales['year'] = sales['record_date'].dt.year
sales['month'] = sales['record_date'].dt.month
sales.head()

  product_id record_date  sales_quantity  inventory_quantity  year  month
0       P001  2023-01-01              56                 219  2023      1
1       P002  2023-01-01              34                 200  2023      1
2       P003  2023-01-01              67                 232  2023      1
3       P004  2023-01-01              98                 518  2023      1
4       P005  2023-01-01              35                 100  2023      1

In [150]:
# checking the product table
product.head()

,ProductID,Product_name,Storage_cost_PLN_per_unit_month,Shelf_life_months,Lead_time_months,Safety_stock_months,Price_PLN_per_unit
0,P001,Product 001,0.34,20,3,0.7,20.62
1,P002,Product 002,0.20,22,2,1.2,10.03
2,P003,Product 003,0.95,15,1,1.1,36.01
3,P004,Product 004,0.67,12,3,1.4,28.22
4,P005,Product 005,1.47,12,2,1.8,84.54

In [151]:
product.columns = product.columns.str.lower()
product.columns

Index(['productid', 'product_name', 'storage_cost_pln_per_unit_month',
       'shelf_life_months', 'lead_time_months', 'safety_stock_months',
       'price_pln_per_unit'],
      dtype='str')

In [152]:
product.rename(columns = {'productid': 'product_id', 'storage_cost_pln_per_unit_month': 'storage_cost_per_unit_month','price_pln_per_unit': 'price_per_unit'}, inplace = True)

product.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   product_id                   250 non-null    str
 1   product_name                 250 non-null    str
 2   storage_cost_per_unit_month  250 non-null    float64
 3   shelf_life_months            250 non-null    int64
 4   lead_time_months             250 non-null    int64
 5   safety_stock_months          250 non-null    float64
 6   price_per_unit               250 non-null    float64
dtypes: float64(3), int64(2), str(2)
memory usage: 13.8 KB

In [153]:
#checking null values
product.isnull().sum()

product_id                     0
product_name                   0
storage_cost_per_unit_month    0
shelf_life_months              0
lead_time_months               0
safety_stock_months            0
price_per_unit                 0
dtype: int64

In [154]:
product.duplicated().value_counts()

False    250
Name: count, dtype: int64

In [155]:
# Checking finance plan table
finance.head()

,ProductID,Product_name,Plan_2023_units,Plan_2024_units,Plan_2025_units,Plan_2023_PLN,Plan_2024_PLN,Plan_2025_PLN,Price_PLN_per_unit
0,P001,Product 001,486,695,543,10021.32,14330.90,11196.66,20.62
1,P002,Product 002,347,376,360,3480.41,3771.28,3610.80,10.03
2,P003,Product 003,599,849,818,21569.99,30572.49,29456.18,36.01
3,P004,Product 004,1024,1920,1693,28897.28,54182.40,47776.46,28.22
4,P005,Product 005,333,406,321,28151.82,34323.24,27137.34,84.54

In [156]:
finance.drop(columns = ['Product_name','Plan_2023_PLN','Plan_2024_PLN','Plan_2025_PLN'],inplace =True)

In [157]:
finance = finance.rename(columns = {'price_pln_per_unit':'price_per_unit'})

In [158]:
finance.columns = finance.columns.str.lower()

In [159]:
finance.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   productid           250 non-null    str
 1   plan_2023_units     250 non-null    int64
 2   plan_2024_units     250 non-null    int64
 3   plan_2025_units     250 non-null    int64
 4   price_pln_per_unit  250 non-null    float64
dtypes: float64(1), int64(3), str(1)
memory usage: 9.9 KB

In [160]:
finance.head()

,productid,plan_2023_units,plan_2024_units,plan_2025_units,price_pln_per_unit
0,P001,486,695,543,20.62
1,P002,347,376,360,10.03
2,P003,599,849,818,36.01
3,P004,1024,1920,1693,28.22
4,P005,333,406,321,84.54

In [161]:
finance.isnull().sum()

productid             0
plan_2023_units       0
plan_2024_units       0
plan_2025_units       0
price_pln_per_unit    0
dtype: int64

In [162]:
finance.duplicated().value_counts()

False    250
Name: count, dtype: int64

Feature Engineering: Adding new columns to understand the avg demand and how many months of inventory coverage we have according to avg demand.

In [163]:
sales['avg_monthly_demand'] = sales.groupby(by = ['product_id','year'])['sales_quantity'].transform('mean')
sales.head()

,product_id,record_date,sales_quantity,inventory_quantity,year,month,avg_monthly_demand
0,P001,2023-01-01,56,219,2023,1,52.666667
1,P002,2023-01-01,34,200,2023,1,32.000000
2,P003,2023-01-01,67,232,2023,1,64.333333
3,P004,2023-01-01,98,518,2023,1,120.500000
4,P005,2023-01-01,35,100,2023,1,32.750000

In [164]:
sales['std_dev_monthly_demand'] = sales.groupby(by = ['product_id','year'])['sales_quantity'].transform('std')
sales['coeff_of_variability'] = sales['std_dev_monthly_demand']/sales['avg_monthly_demand']*100.0
sales.head()

,product_id,record_date,sales_quantity,inventory_quantity,year,month,avg_monthly_demand,std_dev_monthly_demand,coeff_of_variability
0,P001,2023-01-01,56,219,2023,1,52.666667,10.263203,19.487094
1,P002,2023-01-01,34,200,2023,1,32.000000,3.837613,11.992540
2,P003,2023-01-01,67,232,2023,1,64.333333,9.028574,14.034053
3,P004,2023-01-01,98,518,2023,1,120.500000,17.106618,14.196363
4,P005,2023-01-01,35,100,2023,1,32.750000,4.223850,12.897252

In [165]:
sales['inventory_coverage'] = sales['inventory_quantity']/sales['avg_monthly_demand']

In [166]:
sales = pd.merge(sales, product[['product_id','storage_cost_per_unit_month','price_per_unit']], how = 'left', on = 'product_id')
sales.head()

,product_id,record_date,sales_quantity,inventory_quantity,year,month,avg_monthly_demand,std_dev_monthly_demand,coeff_of_variability,inventory_coverage,storage_cost_per_unit_month,price_per_unit
0,P001,2023-01-01,56,219,2023,1,52.666667,10.263203,19.487094,4.158228,0.34,20.62
1,P002,2023-01-01,34,200,2023,1,32.000000,3.837613,11.992540,6.250000,0.20,10.03
2,P003,2023-01-01,67,232,2023,1,64.333333,9.028574,14.034053,3.606218,0.95,36.01
3,P004,2023-01-01,98,518,2023,1,120.500000,17.106618,14.196363,4.298755,0.67,28.22
4,P005,2023-01-01,35,100,2023,1,32.750000,4.223850,12.897252,3.053435,1.47,84.54

In [167]:
# Calculating cost for storing/holding the inventory and the value of inventory

sales['inventory_value'] = sales['inventory_quantity']*sales['price_per_unit']
sales['holding_cost'] = sales['inventory_quantity']*sales['storage_cost_per_unit_month']
sales.head()

,product_id,record_date,sales_quantity,inventory_quantity,year,month,avg_monthly_demand,std_dev_monthly_demand,coeff_of_variability,inventory_coverage,storage_cost_per_unit_month,price_per_unit,inventory_value,holding_cost
0,P001,2023-01-01,56,219,2023,1,52.666667,10.263203,19.487094,4.158228,0.34,20.62,4515.78,74.46
1,P002,2023-01-01,34,200,2023,1,32.000000,3.837613,11.992540,6.250000,0.20,10.03,2006.00,40.00
2,P003,2023-01-01,67,232,2023,1,64.333333,9.028574,14.034053,3.606218,0.95,36.01,8354.32,220.40
3,P004,2023-01-01,98,518,2023,1,120.500000,17.106618,14.196363,4.298755,0.67,28.22,14617.96,347.06
4,P005,2023-01-01,35,100,2023,1,32.750000,4.223850,12.897252,3.053435,1.47,84.54,8454.00,147.00

Calculating required inventory for each product for each month using lead time and safety stock

In [168]:
sales = pd.merge(sales,product[['product_id','lead_time_months','safety_stock_months','shelf_life_months']], how ='left', on = 'product_id' )

In [169]:
sales.head()

,product_id,record_date,sales_quantity,inventory_quantity,year,month,avg_monthly_demand,std_dev_monthly_demand,coeff_of_variability,inventory_coverage,storage_cost_per_unit_month,price_per_unit,inventory_value,holding_cost,lead_time_months,safety_stock_months,shelf_life_months
0,P001,2023-01-01,56,219,2023,1,52.666667,10.263203,19.487094,4.158228,0.34,20.62,4515.78,74.46,3,0.7,20
1,P002,2023-01-01,34,200,2023,1,32.000000,3.837613,11.992540,6.250000,0.20,10.03,2006.00,40.00,2,1.2,22
2,P003,2023-01-01,67,232,2023,1,64.333333,9.028574,14.034053,3.606218,0.95,36.01,8354.32,220.40,1,1.1,15
3,P004,2023-01-01,98,518,2023,1,120.500000,17.106618,14.196363,4.298755,0.67,28.22,14617.96,347.06,3,1.4,12
4,P005,2023-01-01,35,100,2023,1,32.750000,4.223850,12.897252,3.053435,1.47,84.54,8454.00,147.00,2,1.8,12

In [170]:
sales ['inventory_req'] = sales['avg_monthly_demand'] * (sales['lead_time_months'] + sales['safety_stock_months'])

In [171]:
sales = sales.drop(['lead_time_months','safety_stock_months','storage_cost_per_unit_month','price_per_unit'],axis =1)

In [172]:
sales.head()

,product_id,record_date,sales_quantity,inventory_quantity,year,month,avg_monthly_demand,std_dev_monthly_demand,coeff_of_variability,inventory_coverage,inventory_value,holding_cost,shelf_life_months,inventory_req
0,P001,2023-01-01,56,219,2023,1,52.666667,10.263203,19.487094,4.158228,4515.78,74.46,20,194.866667
1,P002,2023-01-01,34,200,2023,1,32.000000,3.837613,11.992540,6.250000,2006.00,40.00,22,102.400000
2,P003,2023-01-01,67,232,2023,1,64.333333,9.028574,14.034053,3.606218,8354.32,220.40,15,135.100000
3,P004,2023-01-01,98,518,2023,1,120.500000,17.106618,14.196363,4.298755,14617.96,347.06,12,530.200000
4,P005,2023-01-01,35,100,2023,1,32.750000,4.223850,12.897252,3.053435,8454.00,147.00,12,124.450000

In [173]:
sales.columns

Index(['product_id', 'record_date', 'sales_quantity', 'inventory_quantity',
       'year', 'month', 'avg_monthly_demand', 'std_dev_monthly_demand',
       'coeff_of_variability', 'inventory_coverage', 'inventory_value',
       'holding_cost', 'shelf_life_months', 'inventory_req'],
      dtype='str')

In [174]:
#Finding the stockouts of products in the year

sales[sales['inventory_quantity']==0][['product_id','year']].value_counts()

product_id  year
P202        2023    3
P214        2023    3
P174        2024    3
P037        2023    2
P099        2023    2
                   ..
P149        2025    1
P017        2025    1
P073        2025    1
P151        2025    1
P248        2025    1
Name: count, Length: 163, dtype: int64

In [ ]:
import urllib.parse
from sqlalchemy import create_engine

# Database settings
host = r"localhost\SQLEXPRESS"
database = "healthcare_inventory"

# Build connection string for Windows Authentication
connection_string = (
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={host};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
)

params = urllib.parse.quote_plus(connection_string)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

# ---------------------------------------------------------
# Upload your 3 DataFrames to SQL Server
# ---------------------------------------------------------

# 1. Upload Sales Table
sales.to_sql("sales", engine, if_exists="append", index=False)

# 2. Upload Product Table
product.to_sql("product", engine, if_exists="append", index=False)

# 3. Upload Finance Table
finance.to_sql("finance", engine, if_exists="append", index=False)

print("All 3 tables (sales, product, finance) uploaded successfully to 'healthcare_inventory'!")

In [ ]:
def stock_status (sales):
    if sales['inventory_quantity'] < sales['inventory_req']:
       return 'understock'
    elif sales['inventory_req'] <= sales['inventory_quantity'] < 1.5 * sales['inventory_req']:
       return 'healthy'
    else:
       return 'overstock'

In [ ]:
sales['stock_status'] = sales.apply(stock_status, axis = 1)
sales[['product_id','inventory_quantity','inventory_req','stock_status']].head()

  product_id  inventory_quantity  inventory_req stock_status
0       P001                 219     194.866667      healthy
1       P002                 200     102.400000    overstock
2       P003                 232     135.100000    overstock
3       P004                 518     530.200000   understock
4       P005                 100     124.450000   understock

In [ ]:
# WARNING: This deletes the old SQL table and creates a brand new one
sales.to_sql("sales", engine, if_exists="replace", index=False)

104

In [ ]:
finance.head()

,productid,plan_2023_units,plan_2024_units,plan_2025_units,price_pln_per_unit
0,P001,486,695,543,20.62
1,P002,347,376,360,10.03
2,P003,599,849,818,36.01
3,P004,1024,1920,1693,28.22
4,P005,333,406,321,84.54

In [ ]:
finance = finance.rename(columns = {'plan_2023_units':'2023','plan_2024_units':'2024','plan_2025_units':'2025'})
finance.columns

Index(['productid', '2023', '2024', '2025', 'price_pln_per_unit'], dtype='str')

In [ ]:
finance = finance.melt(
    id_vars = 'productid',
    value_vars = ['2023','2024','2025'],
    var_name = 'year_planned',
    value_name = 'units_planned'
)

In [ ]:
finance.head()

  productid year_planned  units_planned
0      P001         2023            486
1      P002         2023            347
2      P003         2023            599
3      P004         2023           1024
4      P005         2023            333